add ci for check the pending graphql generated item

diff --git a/.github/workflows/ci-front.yaml b/.github/workflows/ci-front.yaml
--- a/.github/workflows/ci-front.yaml
+++ b/.github/workflows/ci-front.yaml
@@ -44,6 +44,18 @@ jobs:
       - name: Install dependencies
         if: steps.changed-files.outputs.any_changed == 'true' 
         uses: ./.github/workflows/actions/yarn-install
+      - name: GraphQL / Check for Pending Generation
+        if: steps.changed-files.outputs.any_changed == 'true'
+        run: |
+          GRAPHQL_GENERATE_OUTPUT=$(npx nx run twenty-front:graphql:generate || true)
+          GRAPHQL_METADATA_OUTPUT=$(npx nx run twenty-front:graphql:generate --configuration=metadata || true)
+          if [[ $GRAPHQL_GENERATE_OUTPUT == *"No changes detected"* && $GRAPHQL_METADATA_OUTPUT == *"No changes detected"* ]]; then
+            echo "GraphQL generation check passed."
+          else
+            echo "::error::Unexpected GraphQL changes detected. Please run the required commands and commit the changes."
+            echo "$GRAPHQL_GENERATE_OUTPUT"
+            echo "$GRAPHQL_METADATA_OUTPUT"
+            exit 1
       - name: Diagnostic disk space issue
         if: steps.changed-files.outputs.any_changed == 'true'
         run: df -h
