add ci for check the pending graphql generated item

diff --git a/.github/workflows/ci-server.yaml b/.github/workflows/ci-server.yaml
--- a/.github/workflows/ci-server.yaml
+++ b/.github/workflows/ci-server.yaml
@@ -98,18 +98,22 @@ jobs:
             exit 1
           fi
       - name: GraphQL / Check for Pending Generation
-        if: steps.changed-files.outputs.any_changed == 'true'
         run: |
-          GRAPHQL_GENERATE_OUTPUT=$(npx nx run twenty-front:graphql:generate || true)
-          GRAPHQL_METADATA_OUTPUT=$(npx nx run twenty-front:graphql:generate --configuration=metadata || true)
-          if [[ $GRAPHQL_GENERATE_OUTPUT == *"No changes detected"* && $GRAPHQL_METADATA_OUTPUT == *"No changes detected"* ]]; then
-            echo "GraphQL generation check passed."
-          else
-            echo "::error::Unexpected GraphQL changes detected. Please run the required commands and commit the changes."
-            echo "$GRAPHQL_GENERATE_OUTPUT"
-            echo "$GRAPHQL_METADATA_OUTPUT"
-            exit 1    
-          fi
+         GRAPHQL_GENERATION_OUTPUT=$(npx nx run twenty-front:graphql:generate || true)
+
+         GRAPHQL_METADATA_OUTPUT=$(npx nx run twenty-front:graphql:generate --configuration=metadata || true)
+
+         GENERATED_GRAPHQL_FILE=$(ls packages/twenty-front/*graphql.ts 2>/dev/null || echo "")
+    
+         if [ -n "$GENERATED_GRAPHQL_FILE" ]; then
+          echo "::error::GraphQL generation is pending. Please run the GraphQL generation commands before committing."
+          echo "$GRAPHQL_GENERATION_OUTPUT"
+          echo "$GRAPHQL_METADATA_OUTPUT"
+      
+          rm -f packages/twenty-front/*graphql.ts
+
+          exit 1
+        fi
       - name: Save server setup
         uses: ./.github/workflows/actions/save-cache
         with:
