add ci for check the pending graphql generated item

diff --git a/.github/workflows/ci-server.yaml b/.github/workflows/ci-server.yaml
--- a/.github/workflows/ci-server.yaml
+++ b/.github/workflows/ci-server.yaml
@@ -78,21 +78,7 @@ jobs:
           npx nx run twenty-server:database:init:prod
           npx nx run twenty-server:database:migrate:prod
       - name: Worker / Run
-        run: |
-         npx nx run twenty-server:worker:ci
-      - name: GraphQL / Check for Pending Generation
-        if: steps.changed-files.outputs.any_changed == 'true'
-        run: |
-          GRAPHQL_GENERATE_OUTPUT=$(npx nx run twenty-front:graphql:generate || true)
-          GRAPHQL_METADATA_OUTPUT=$(npx nx run twenty-front:graphql:generate --configuration=metadata || true)
-         if [[ $GRAPHQL_GENERATE_OUTPUT == *"No changes detected"* && $GRAPHQL_METADATA_OUTPUT == *"No changes detected"* ]]; then
-           echo "GraphQL generation check passed."
-           else
-           echo "::error::Unexpected GraphQL changes detected. Please run the required commands and commit the changes."
-           echo "$GRAPHQL_GENERATE_OUTPUT"
-           echo "$GRAPHQL_METADATA_OUTPUT"
-           exit 1    
-          fi  
+        run: npx nx run twenty-server:worker:ci
       - name: Server / Check for Pending Migrations
         run: |
           METADATA_MIGRATION_OUTPUT=$(npx nx run twenty-server:typeorm migration:generate metadata-migration-check -d src/database/typeorm/metadata/metadata.datasource.ts || true)
@@ -110,6 +96,19 @@ jobs:
             rm -f packages/twenty-server/*metadata-migration-check.ts packages/twenty-server/*core-migration-check.ts
             
             exit 1
+          fi
+      - name: GraphQL / Check for Pending Generation
+         if: steps.changed-files.outputs.any_changed == 'true'
+        run: |
+          GRAPHQL_GENERATE_OUTPUT=$(npx nx run twenty-front:graphql:generate || true)
+          GRAPHQL_METADATA_OUTPUT=$(npx nx run twenty-front:graphql:generate --configuration=metadata || true)
+         if [[ $GRAPHQL_GENERATE_OUTPUT == *"No changes detected"* && $GRAPHQL_METADATA_OUTPUT == *"No changes detected"* ]]; then
+           echo "GraphQL generation check passed."
+           else
+           echo "::error::Unexpected GraphQL changes detected. Please run the required commands and commit the changes."
+           echo "$GRAPHQL_GENERATE_OUTPUT"
+           echo "$GRAPHQL_METADATA_OUTPUT"
+           exit 1    
           fi
       - name: Save server setup
         uses: ./.github/workflows/actions/save-cache
